### ISSUE TITLE
How are you adapting this to mobile?

### ISSUE THREAD

**Issue by Shoshin23** [KleinYuan/caffe2-yolo#1]
Hey! 
I've been trying to get YOLO setup using Caffe2 but been running into issues. Also, have you bridged the mobile gap? Got it working on mobile yet?

**Comment by XiomarG** [comment]
It's working on mobile. Please be more specific on your issues.

**Comment by KleinYuan** [comment]
@Shoshin23 almost there man.
Check this out:https://github.com/KleinYuan/Caffe2-iOS/pull/12

We will merge it soon. 

Not quite sure about the quality of the yolo model yet. But with this version, you can test it now.

**Comment by Shoshin23** [comment]
I'm sorry @XiomarG, I didnt go through the other repo(caffe2-ios) to check for changes. I did try out Yolo and LeNet but couldnt make sense of the output. I'll go through the code to understand better. 
Thanks!
